networks:
  omada-net:
    driver: bridge
  reverse-proxy:
    external: true

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    networks:
      - omada-net
      - reverse-proxy
    environment:
      TZ: Europe/Vilnius
    volumes:
      - ./config:/config
    # ports:
    #   - "8123:8123"

  omada:
    image: mbentley/omada-controller:latest
    container_name: omada
    restart: unless-stopped
    networks:
      - omada-net
      - reverse-proxy
    environment:
      TZ: ${TZ}
    volumes:
      - ./data:/opt/tplink/EAPController/data
      - ./logs:/opt/tplink/EAPController/logs
      - ./work:/opt/tplink/EAPController/work
    ports:
      - "8043:8043/tcp"
      - "8088:8088/tcp"
      - "8843:8843/tcp"
      - "27001:27001/udp"
      - "29810:29810/udp"
      - "29811-29817:29811-29817/tcp"
      
